version: '3.8'
services:
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  keycloak:
    # Starting with Keycloak 17, Keycloak is now powered by Quarkus and no longer WildFly
    # This requires slight changes to the configuration, see https://www.keycloak.org/migration/migrating-to-quarkus
    image: quay.io/keycloak/keycloak:21.1.2
    command: [ 'start-dev --http-relative-path /auth --import-realm --auto-build' ]
    environment:
      - KEYCLOAK_DB=dev-file
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KEYCLOAK_FEATURES=scripts
    volumes:
      - type: bind
        source: ./tmp
        target: /opt/keycloak/data/import
        read_only: true
    ports:
    - "8888:8080"
  # Drop-in replacement for the previous roribio16/alpine-sqs:latest (which had no arm64 support)
  sqs:
    image: softwaremill/elasticmq-native
    volumes:
      - type: bind
        source: ./tmp/sqs-queue-definition.conf
        target: /opt/elasticmq.conf
        read_only: true
    ports:
      - "9324:9324"
      - "9325:9325"
